### ISSUE TITLE
reloadDataAnimated crash app

### ISSUE THREAD

**Issue by felipecastro** [KieranLafferty/KLNoteViewController#15]
Hello, tks for the control, it is amazing! but i face a strange situation, I have a button that when clicked in view triggers [self reloadDataAnimated: YES] and each time it is clicked it decreases the performance of the application and after a few clicks makes app crash. What am I doing wrong?

**Comment by dexcell** [comment]
There is probably something in your viewcontroller, because in my opinion reloadDataAnimated done it correctly and does not decrease the performance.
