### ISSUE TITLE
hidesBottomBarWhenPushed does not work

### ISSUE THREAD

**Issue by dexcell** [KieranLafferty/KLNoteViewController#17]
If you attach the KLNoteViewController to a UITabBarController then you cannot do the <code>hidesBottomBarWhenPushed</code> on the child view when pushing to navigationController.

I've searched through google and cannot found way to fix this, though i know the reason because UINavigationController was not the direct child of UITabbarController.

Right now my only way to do it is manually hiding the tabbar when pushing the view, but again it does not looks when the native do it.

Any idea for this, probably some kind of way to relay this hidesBottomBarWhenPushed message to the UITabBar? 
Thanks

**Comment by KieranLafferty** [comment]
Hey Dexcell,

I implemented a UITabBarController nested into a UINavigationController as a card in KLNoteViewController with the hidesBottomBarWhenPushed enabled. In my tests the behavior of worked as expected and the Tab Bar was removed on push and restored on pop of the UINavigationController. 

Marking this one was working as designed.
