### ISSUE TITLE
<Error>: CGAffineTransformInvert: singular matrix.

### ISSUE THREAD

**Issue by iamaunz** [KieranLafferty/KLNoteViewController#23]
Hi, Thank you for your great KLNoteViewController.
I try to use your code in my project (without xib and story board)
1. I have MainPage subclass from KLNoteViewController
2. I follow your tutorial step by step
3. I got this message "<Error>: CGAffineTransformInvert: singular matrix."
4. Nothing appear in my ViewController

I can run your example code but I can't use it in my project.
thank for help.

**Comment by KieranLafferty** [comment]
Will need more information, when does this occur, can you trace the code in KLNoteViewController.m to find out which line is causing this?

**Comment by KieranLafferty** [comment]
Will close until more details (steps to reproduce, code samples) are provided. Please let me know  if you are still experiencing this with the latest code pushed
