### ISSUE TITLE
Hide Navigation Bar on Show

### ISSUE THREAD

**Issue by austimkelly** [KieranLafferty/KLNoteViewController#27]
Nice piece of work. I found this useful for my app:

+#define kHideNavigationBarOnShow YES

-(void) toggleStateAnimated:(BOOL) animated {
     KLControllerCardState nextState = self.state == KLControllerCardStateDefault ? KLControllerCardStateFullScreen : KLControllerCardStateDefault;
-   
  +#if kHideNavigationBarOnShow == YES
-    if (nextState == KLControllerCardStateFullScreen){
-        [self.noteViewController.navigationController setNavigationBarHidden:YES animated:YES];
-    } else {
-        [self.noteViewController.navigationController setNavigationBarHidden:NO animated:YES];
-    }
  +#endif
-   
   [self setState: nextState
         animated: animated];
  }

**Comment by KieranLafferty** [comment]
Great stuff, thanks
