### ISSUE TITLE
Sizing/ Scaling issue

### ISSUE THREAD

**Issue by aardvark-tar** [KieranLafferty/KLNoteViewController#28]
![ios simulator screen shot 23 nov 2013 1 48 18 pm](https://f.cloud.github.com/assets/4143578/1605919/ef86a210-5402-11e3-91ea-b66356b52cd2.png)
![ios simulator screen shot 23 nov 2013 1 48 27 pm](https://f.cloud.github.com/assets/4143578/1605920/f4eba9a8-5402-11e3-8119-872f7ed5ca7e.png)

**Comment by ercancelik** [comment]
Any progress?

**Comment by sbfucker** [comment]
How can i resolve that problem~？

**Comment by KieranLafferty** [comment]
I need a way to repro this if I am going to fix it :)

**Comment by sbfucker** [comment]
please。。。I use this program BUT it can`t use in iOS7

**Comment by KieranLafferty** [comment]
see previous comment

**Comment by KieranLafferty** [comment]
Closing because no repro
