### ISSUE TITLE
A question... reload controller

### ISSUE THREAD

**Issue by nokai** [KieranLafferty/KLNoteViewController#3]
I love it! You have been very good. Congrats.  A question ... How I can I reload/update (new data) a controller from another?

**Comment by KieranLafferty** [comment]
Hello Nokai, the control follows the same pattern as UITableView. Simply call the -reloadData method and it will grab the data from the defined datasource methods below: 

//Called when the NoteViewController needs to know how many controller cards to expect
- (NSInteger)numberOfControllerCardsInNoteView:(KLNoteViewController*) noteView;
  //Called to populate the controllerCards array - Automatically maps the UINavigationController to KLControllerCard and adds to array
- (UIViewController _)noteView:(KLNoteViewController_)noteView viewControllerForRowAtIndexPath:(NSIndexPath *)indexPath;

Be sure to update the data that gets sent to these methods BEFORE calling the reloadData.

**Comment by nokai** [comment]
Hello

Sorry but I find impossible from a viewcontroller already loaded, call another viewcontroller loaded and change.

Nor do I find the way from one viewcontroller up, call another and upload.

Maybe I'm too clumsy.

If you put me I'd appreciate an example.

thank you very much

**Comment by KieranLafferty** [comment]
Hey Nokai, I added a function that performs a reload in an animated fashion:

```
-(void) reloadDataAnimated:(BOOL) animated;
```

Try this out on the latest source in both animated = YES, and animated = NO. Let me know how it works for you.

**Comment by nokai** [comment]
Ok, I understand that. But my question was called a KLControllerCard from another (KLCustomViewController)

I want to pass data from one to another.

Thanks again

**Comment by nokai** [comment]
I've got ... you can close issue

Greetings
