### ISSUE TITLE
Change State of KLControllerCard

### ISSUE THREAD

**Issue by paoloandrea** [KieranLafferty/KLNoteViewController#4]
Hi, thank for you work, is a beautiful component.
I've a question:
How can I change KLControllerCardState in a view if it is open?

**Comment by KieranLafferty** [comment]
Hello Paolo,

Not sure what you mean by "in a view if it is open" but you can change the state by getting a reference to the KLControllerCard that you wish to and performing the following

```
//Arbitrarily get the first card
KLControllerCard* card = [noteView.controllerCards objectAtIndex: 0];
[card setState: KLControllerCardStateDefault animated: YES];
```

Hopefully this answers your question

**Comment by paoloandrea** [comment]
Thank you. That work!
