### ISSUE TITLE
How can I get the size of noteView opened and closed?

### ISSUE THREAD

**Issue by paoloandrea** [KieranLafferty/KLNoteViewController#5]
Hi, thank's to help me.
Now i've another question.
In the noteView in first plane i have a tableView.
How can i detect the size of the noteView closed and the size of the noteView opened.
Thank's so much.
p

**Comment by KieranLafferty** [comment]
Hey Paulo.

The control uses a CALayer transform to grow/shrink the UIViewController. This means that everything gets shrunk proportionally. Is there a specific reason why you need to know the width? 

I havent tested, but within the tableview View Controller you could do a self.view.frame.size.width to get the width. Although I havent had a chance to test the affect of the transform on this property

**Comment by paoloandrea** [comment]
I need to know the height, not the width of the view closed.
In my project, the view contains a tableview with many fields, to work properly, the slider, I have to resize the height of the table for any action to resize.

**Comment by KieranLafferty** [comment]
Are you getting positioning issues when the view is resized? It should just be visually smaller but maintain the same properties on your view controller 

Regards,

Kieran Lafferty
