### ISSUE TITLE
Long press then slide the card is not working

### ISSUE THREAD

**Issue by dulacp** [KieranLafferty/KLNoteViewController#9]
When you perform a long press on a card you aren't able to slide it anymore, it's like the UI is "freezing" but it's not. In fact the long press seems to take the lead on the pan gesture handle by the method `didPerformPanGesture:`.

A good solution would be to add a new boolean configuration `enableLongPress` that would be true by default to be backward compatible, and that would decide if we instantiate or not a `UILongPressGestureRecognizer`.

This way everybody is happy I think.
I'll post a commit for that suggestion today.

**Comment by KuroroSam** [comment]
For this issue, it is better to implement shouldRecognizeSimultaneouslyWithGestureRecognizer.

I will push my code later.
Thx
